### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ArcticLatent** [WickedLukas/nvidia-tuner#3]
![nvidia_uv](https://github.com/user-attachments/assets/8567f2d5-8f70-4b12-894e-2e4207ac9fac)

I undervolt my Nvidia card with these settings in windows msi afterburner. Can you help me to convert these into your scripts parameters please?

Thanks!

**Comment by WickedLukas** [comment]
Hi, you should come very close to this by setting a core clock offset of 150 mhz and a memory clock offset of 1000 mhz, while lowering the power limit so far, until you get similar performance in game. Alternatively you can also check your current power usage during gaming and set this as a limit. You will be limited by power instead of frequency, but in the end the result is very similar.

**Comment by ArcticLatent** [comment]
Okay I tried to use your script . tried it with
./nvidia-tuner --core-clock-offset 150 --memory-clock-offset 800 --power-limit 180 --pairs 50:30,70:40,90:60,100:100

it asks for sudo password and when I enter password. it just stucks nothing happens

**Comment by WickedLukas** [comment]
No, it is not stuck. It applied the overclock/undervolt and since you provided a fan curve, it is running and adjusting the fan speed. If you stop it by pressing ctrl+c for example, it will print that it reset the fan speed back to default.
